### ISSUE TITLE
Swift 4 support required

### ISSUE THREAD

**Issue by rajahimanath** [luannguyenkhoa/LNSideMenu#10]

**Comment by luannguyenkhoa** [comment]
It was in my plan. Hopefully, it is able to go live in this weekend.

**Comment by rajahimanath** [comment]
Any updates pls!!

**Comment by luannguyenkhoa** [comment]
@rajahimanath 
A new release `3.0` that supports Swift 4 is available now. Please check it out and get back to me if any. Thanks for your attention.

**Comment by luannguyenkhoa** [comment]
I'm gonna close this issue. Feel free to file another one relatively if any.
