### ISSUE TITLE
Dynamic values for side menu

### ISSUE THREAD

**Issue by developweb10** [luannguyenkhoa/LNSideMenu#13]
I need to display dynamic values for side menu.how can i achieve this.

**Comment by luannguyenkhoa** [comment]
Sorry for being late on the reply.

What did you mean about `dynamic values`? The lib enables an ability on refreshing the menu with a new list of items: `sideMenu.refreshMenu(items)`
This's what you're looking for?
Give me more details if not. 
Thanks for your attention.

**Comment by luannguyenkhoa** [comment]
Close the thread because of lack of activities
