### ISSUE TITLE
How to achieve second style of side menu

### ISSUE THREAD

**Issue by PramodShukla10** [luannguyenkhoa/LNSideMenu#14]

**Comment by luannguyenkhoa** [comment]
Please refer to this link for your expectation: https://github.com/luannguyenkhoa/LNSideMenu#using-your-own-menu

Follow the example for implementing your custom menu.
Thanks.

**Comment by PramodShukla10** [comment]
show me the code for getting effect like second screenshot.

**Comment by PramodShukla10** [comment]
sideMenuManager?.sideMenuController()?.sideMenu?.disabled = true

not working properly some time it does open menu on swipe.

**Comment by luannguyenkhoa** [comment]
Seems you're looking at wrong viewcontroller.
For the default style menu (left), navigating to the destination `ContentViewController` when selecting a cell.
For the custom menu, the segue destination is `NextViewController`.

**Comment by PramodShukla10** [comment]
For the default style menu (left), navigating to the destination ContentViewController when selecting a cell.

after that on ContentViewController  interactivePopGestureRecognizer working if partially swipe this controller and leave it,then again swipe same controller menu will be open.

in short default navigation controller back  interactivePopGestureRecognizer conflict with menu gesture.

**Comment by luannguyenkhoa** [comment]
Thanks for catching it. Lemme check.

**Comment by luannguyenkhoa** [comment]
the cause is because we set `disabled = true` in viewDidLoad, it should be located in viewWillAppear.
btw, I just published a new version that fixes outstanding issues and updated example. 
Please take a look if you are still here.
