### ISSUE TITLE
After updating pod, is needed to change in code, lots of error 

### ISSUE THREAD

**Issue by PramodShukla10** [luannguyenkhoa/LNSideMenu#15]

**Comment by luannguyenkhoa** [comment]
Hi man,

I have shortened these two function and property name in the latest version:
`sideMenuController()` -> `instance()`
`.sideMenu` -> `.menu`
The purpose is to make the code shorter and more readable.
Sorry for this inconvenience, please help to update them.

**Comment by luannguyenkhoa** [comment]
close because of lack of activities
