### ISSUE TITLE
Side menu

### ISSUE THREAD

**Issue by karthickkck315** [luannguyenkhoa/LNSideMenu#19]
How can I achieve the first type of side menu?

**Comment by hoangtran-agilityio** [comment]
The example to guide how to archive both the first and second types is available on this repo, please follow to get it worked for your demand. You can make an attempt with the example to see how the default and custom menus work by enabling/disabling 2 lines: 21 & 23 respectively. [here](https://github.com/luannguyenkhoa/LNSideMenu/blob/ef22b77871ad5dc22e3725438c6b0ee83db34e95/Example/LNSideMenu/SMNavigationController.swift#L21)
Thanks.

**Comment by luannguyenkhoa** [comment]
The example to guide how to archive both the first and second types is available on this repo, please follow to get it worked for your demand. You can make an attempt with the example to see how the default and custom menus work by enabling/disabling 2 lines: 21 & 23 respectively. [Here you are](https://github.com/luannguyenkhoa/LNSideMenu/blob/ef22b77871ad5dc22e3725438c6b0ee83db34e95/Example/LNSideMenu/SMNavigationController.swift#L21).
Thanks.

**Comment by karthickkck315** [comment]
Thank you so much Got it...
