### ISSUE TITLE
Bug after coming back from Photo Library?

### ISSUE THREAD

**Issue by rgillyproj** [luannguyenkhoa/LNSideMenu#2]
Love the menu. Putting it in a project right now and came across an issue.

The side menu seems to shift up when I come back from the UIImagePickerController. The issue remains proportional in shifting when `sideMenu?.underNavigationBar = true` is also enabled when initialized.

The code that is accessing the photo library is quite standard. Here's a portion:
```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        if picker.sourceType == UIImagePickerControllerSourceType.photoLibrary || picker.sourceType == UIImagePickerControllerSourceType.camera {
            if let image = info[UIImagePickerControllerOriginalImage] as? UIImage {
                photoImage.image = image
            }
        }
        
        dismiss(animated: true, completion: nil)
    }
```

Here is a gif for a better visual:
![oct-11-2016 15-42-39](https://cloud.githubusercontent.com/assets/16105656/19285969/1bcd2802-8fca-11e6-9ab5-148a3d83bb5b.gif)

Not sure what the quick fix would be. Going to keep investigating. If you have any suggestions for a fix, it'd be greatly appreciated.

**Comment by luannguyenkhoa** [comment]
``sideMenu?.underNavigationBar = true`` just be used for the custom menu only. 
No need to enable it when initializing the default menu.

Regard to your issue, i suppose that the content view's navigation bar is transparent at first appearance, then the navigation bar no longer transparent after coming back from Photo library .
it causes the issue. Correct me if any.

I suggest you should set ``isNavbarHiddenOrTransparent`` value whenever the navigation bar is changed to transparent or non-transparent, respectively.

I haven't noted this yet, sorry for confusing you.
Thanks for posting the issue.

**Comment by rgillyproj** [comment]
Thanks for your help. In my upload photo VC,

`sideMenuManager?.sideMenuController()?.sideMenu?.isNavbarHiddenOrTranslucent = false`

 on viewWillAppear did the trick. It now behaves much nicer.
