### ISSUE TITLE
Dismiss on tap outside

### ISSUE THREAD

**Issue by CKzu** [luannguyenkhoa/LNSideMenu#5]
Hello and thanks for the great job!

Simple question here, is there a way to dismiss the menu by tapping outside of it? I haven't found any property or method allowing that in your code.

Thanks in advance!

**Comment by luannguyenkhoa** [comment]
Sorry for late reply, I already missed this message because there were too many notifications from github in this period.
Regarding to your question, it was out of scope of the current release.
It will be in the updates list. I'm planning to release a new one.

**Comment by CKzu** [comment]
Thanks for your reply.
Is there by any chance a workaround I could implement to get the feature before you update the lib?

**Comment by luannguyenkhoa** [comment]
Of course, you do have the ability to implement the feature yourself.
Folk to your repo and then do something like this:
```
let tapGesture = UITapGestureRecognizer(target: self, action: #selector(tapGesture(tapGesture:)))
contentView.addGestureRecognizer(tapGesture)
```
Adding this initialization into `func addGesture(` in LNSideMenu class.
```
internal func tapGesture(tapGesture: UIGestureRecognizer){
    if let custom = customMenu?.view {
      if custom.frame.contains(tapGesture.location(in: sideMenuContainerView)) {
        toggleMenu()
      }
    } else {
      toggleMenu()
    }
  }
```
The `selector` above is supporting for both default curve menu and custom menu.
That's all.
Anw, thanks for your attention.

**Comment by CKzu** [comment]
Awesome! Thanks for your help

**Comment by luannguyenkhoa** [comment]
I will close this. Feel free to reopen if any.
