### ISSUE TITLE
Menu delegate not called when menu is open via panGesture : func panToogleMenu(_ show: Bool)

### ISSUE THREAD

**Issue by NivekAlunya** [luannguyenkhoa/LNSideMenu#7]
Used to add this line in : 

fileprivate func panToogleMenu(_ show: Bool) {
    var centerx = sourceView.center.x
    if !show {
      centerx = position == .left ? -sourceView.width/2 : sourceView.width + sourceView.width/2
    }
    isMenuOpen = show
    UIView.animate(withDuration: animationDuration, animations: {
      self.sideMenuContainerView.center.x = centerx
    }) { _ in
      self.animationCompleted = true
      **_self.isMenuOpen ? self.delegate?.sideMenuDidOpen?() : nil_**
    }
    // Starting show/hide blur view animation
    animateBlurview(isShow: show)
  }

In further release can u patch your code for calling the delegate on all the kinds of opening the menu ?

**Comment by luannguyenkhoa** [comment]
Thanks for your attention.

Just would like to inform that it's in the next release. 
A new one will go out soon.

**Comment by luannguyenkhoa** [comment]
Be informed that your request is available in v2.3.
I'm gonna close this thread. Feel free to reopen if any. 
Thanks.
