### ISSUE TITLE
didSelectRowAt not firing

### ISSUE THREAD

**Issue by ajonno** [luannguyenkhoa/LNSideMenu#9]
I'm sure it's something obvious but after downloading and running the app, and setting a breakpoint in didSelectRowAt() method, row taps are not being recognised

both the delegate and datasource appear to be connected in IB.

**Comment by luannguyenkhoa** [comment]
Hi @ajonno,
Could you show me what version of the lib your project is pointing to? 
It's the latest release `2.3.2`, isn't it?

**Comment by luannguyenkhoa** [comment]
No response for a long time. 
I'm gonna close this issue.
